# Generated by Django 5.2.6 on 2025-12-12 11:04

import accounts.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=20)),
                ('id_front', models.FileField(blank=True, null=True, upload_to=accounts.utils.id_front_upload_path)),
                ('id_back', models.FileField(blank=True, null=True, upload_to=accounts.utils.id_back_upload_path)),
                ('dl_front', models.FileField(blank=True, null=True, upload_to=accounts.utils.dl_front_upload_path)),
                ('dl_back', models.FileField(blank=True, null=True, upload_to=accounts.utils.dl_back_upload_path)),
                ('business_license', models.FileField(blank=True, null=True, upload_to=accounts.utils.business_license_upload_path)),
                ('face_photo', models.FileField(blank=True, null=True, upload_to=accounts.utils.face_photo_upload_path)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserDocument',
        ),
    ]
