# Generated by Django 5.2.6 on 2025-12-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_document_delete_userdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='role',
        ),
    ]
